### ISSUE TITLE
How do we package and deploy these samples?

### ISSUE THREAD

**Issue by lyoungblood** [aws-samples/aws-cloudhsm-on-aws-lambda-sample#1]
We are very interested in using CloudHSM with Lambda, but this repository seems to only be linking to Java samples that require connection to a full `cloudhsm-client` running on a Linux server somewhere. The CloudHSM client software runs as daemon processes that require systemd, so they are not a good fit for Lambda or even Docker containers.

Can you provide any guidance on how to package and deploy Lambda functions that interact with CloudHSM natively?

**Comment by mohamed-osama-aboelkheir** [comment]
Apologies for the delayed response, the full details of how to use this sample have been posted on the AWS Security blog post https://aws.amazon.com/blogs/security/how-to-run-aws-cloudhsm-workloads-on-aws-lambda/
